# Generated by Django 4.2.1 on 2023-05-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='creator',
        ),
    ]
